# Generated by Django 4.0.1 on 2022-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcd', '0003_alter_plan_plan_activity_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_dateOfJoin',
            field=models.DateField(),
        ),
    ]
